### ISSUE TITLE
How do you remove any applied filters?

### ISSUE THREAD

**Issue by mattpurlandncc** [vincjo/datatables#15]
Not sure if I'm missing something, but how do you remove any applied filters?

For example, I'm not using the table headers/input field to filter data - but programmatically using radio buttons, and so I need to be able to programmatically reset the filters

**Comment by vincjo** [comment]
I just exposed the method in the DataHandler.
As there is `handler.clearSearch()`, there is now `handler.clearFilters()`

The problem is that the input values ​​are not bound with the filters store.
I haven't looked yet if I can go further, please let me know if this can be improved

You can test the method here:
https://vincjo.fr/datatables/test

**Comment by mattpurlandncc** [comment]
@vincjo works perfectly, thanks
